name: Dump Context
runs:
  using: composite
  steps:
    - run: |
        printf "%30s = %s\n" github.base_ref ${{github.base_ref }}
        printf "%30s = %s\n" github.event.inputs.dry-run ${{ github.event.inputs.dry-run }}
        printf "%30s = %s\n" github.event.ref ${{ github.event.ref }}
        printf "%30s = %s\n" github.event_name ${{ github.event_name }}
        printf "%30s = %s\n" github.head_ref ${{github.head_ref }}
        printf "%30s = %s\n" github.ref ${{ github.ref }}
        printf "%30s = %s\n" github.ref_name ${{ github.ref_name }}
        printf "%30s = %s\n" inputs.dry-run ${{ inputs.dry-run }}
